# Generated by Django 5.0.6 on 2024-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
    ]
