# Generated by Django 5.0.6 on 2024-07-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('sample_number', models.IntegerField(primary_key=True, serialize=False)),
                ('core_number', models.IntegerField()),
                ('sec', models.CharField(max_length=50)),
                ('chainage', models.IntegerField()),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.job')),
            ],
            options={
                'unique_together': {('job_number', 'core_number')},
            },
        ),
    ]
