# Generated by Django 5.0.6 on 2024-07-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=30)),
                ('sample_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.core')),
            ],
        ),
    ]
